name: CDK Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to deploy to dev"
        required: true
        default: main

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: us-east-1
  STACK_NAME: infra
  NODE_VERSION: 22.11.0

jobs:
  deploy-dev:
    environment: dev
    runs-on: ubuntu-latest
    name: Deploy to Dev

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: garden
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch || github.ref_name }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install all workspaces
        run: npm ci

      - name: Run API tests
        working-directory: apps/api
        run: npm test

      - name: Install infra deps
        working-directory: infra
        run: npm ci

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install AWS CDK CLI
        run: npm install -g aws-cdk@latest

      - name: Deploy Infrastructure (Dev)
        working-directory: infra
        run: |
          cdk deploy $STACK_NAME-dev \
            --require-approval never \
            -c stage=dev \
            --parameters DbUser=${{ vars.DB_USER }} \
            --parameters DbPassword=${{ secrets.DB_PASSWORD }}

      - name: Run DB migrations (Dev)
        run: |
          MIGRATE_FN=$(aws cloudformation describe-stacks \
            --stack-name $STACK_NAME-dev \
            --query "Stacks[0].Outputs[?OutputKey=='MigrateFnName'].OutputValue" \
            --output text)
          aws lambda invoke --function-name "$MIGRATE_FN" response.json --log-type Tail > result.json
          cat response.json
          FUNCTION_ERROR=$(jq -r '.FunctionError // empty' result.json)
          if [ -n "$FUNCTION_ERROR" ]; then
            echo "❌ Migration Lambda failed"
            exit 1
          fi

      - name: Inject build metadata
        run: |
          COGNITO_DOMAIN=$(aws cloudformation describe-stacks \
            --stack-name $STACK_NAME-dev \
            --query "Stacks[0].Outputs[?OutputKey=='CognitoDomain'].OutputValue" \
            --output text)
          COGNITO_USER_POOL_ID=$(aws cloudformation describe-stacks \
            --stack-name $STACK_NAME-dev \
            --query "Stacks[0].Outputs[?OutputKey=='UserPoolId'].OutputValue" \
            --output text)
          COGNITO_USER_POOL_CLIENT_ID=$(aws cloudformation describe-stacks \
            --stack-name $STACK_NAME-dev \
            --query "Stacks[0].Outputs[?OutputKey=='UserPoolClientId'].OutputValue" \
            --output text)

          echo "COGNITO_DOMAIN: $COGNITO_DOMAIN"

          # api env vars
          echo "AWS_REGION=${{ env.AWS_REGION }}" >> apps/api/.env
          echo "AWS_COGNITO_JWKS_URI=https://cognito-idp.${{ env.AWS_REGION }}.amazonaws.com/${COGNITO_USER_POOL_ID}/.well-known/jwks.json" >> apps/api/.env
          echo "AWS_COGNITO_USER_POOL_URL=https://cognito-idp.${{ env.AWS_REGION }}.amazonaws.com/${COGNITO_USER_POOL_ID}" >> apps/api/.env

          # Web env vars
          echo "VITE_BUILD_ID=${{ github.run_number }}" >> apps/web/.env
          echo "VITE_COMMIT_SHA=${{ github.sha }}" >> apps/web/.env
          echo "VITE_API_BASE_URL=https://e75x4uq227.execute-api.${{ env.AWS_REGION }}.amazonaws.com" >> apps/web/.env
          echo "VITE_AWS_REGION=${{ env.AWS_REGION }}" >> apps/web/.env
          echo "VITE_COGNITO_USER_POOL_CLIENT_ID=${COGNITO_USER_POOL_CLIENT_ID}" >> apps/web/.env
          echo "VITE_COGNITO_DOMAIN=${COGNITO_DOMAIN}" >> apps/web/.env
          echo "VITE_COGNITO_USER_POOL_ID=${COGNITO_USER_POOL_ID}" >> apps/web/.env

          # Debug output
          echo "Contents of apps/web/.env:"
          cat apps/web/.env

      - name: Install web build dependencies
        run: npm install @rollup/rollup-linux-x64-gnu --workspace apps/web --no-save

      - name: Build frontend
        run: npm run build --workspace apps/web

      - name: Upload frontend to S3
        run: |
          BUCKET=$(aws cloudformation describe-stacks \
            --stack-name $STACK_NAME-dev \
            --query "Stacks[0].Outputs[?OutputKey=='SiteBucketName'].OutputValue" \
            --output text)
          echo "Deploying to $BUCKET"
          aws s3 sync apps/web/dist s3://$BUCKET --delete

      - name: Invalidate CloudFront cache
        run: |
          DIST_ID=$(aws cloudformation describe-stacks \
            --stack-name $STACK_NAME-dev \
            --query "Stacks[0].Outputs[?OutputKey=='SiteDistributionId'].OutputValue" \
            --output text)
          echo "Invalidating distribution $DIST_ID"
          aws cloudfront create-invalidation --distribution-id $DIST_ID --paths "/*"

  deploy-prod:
    environment: prod
    runs-on: ubuntu-latest
    name: Deploy to Prod
    needs: deploy-dev
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install all workspaces
        run: npm ci

      - name: Install infra deps
        working-directory: infra
        run: npm ci

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install AWS CDK CLI
        run: npm install -g aws-cdk@latest

      - name: Deploy Infrastructure (Prod)
        working-directory: infra
        run: |
          cdk deploy $STACK_NAME-prod \
            --require-approval never \
            -c stage=prod \
            --parameters DbUser=${{ vars.DB_USER }} \
            --parameters DbPassword=${{ secrets.DB_PASSWORD }}

      - name: Run DB migrations (Prod)
        run: |
          MIGRATE_FN=$(aws cloudformation describe-stacks \
            --stack-name $STACK_NAME-prod \
            --query "Stacks[0].Outputs[?OutputKey=='MigrateFnName'].OutputValue" \
            --output text)
          aws lambda invoke --function-name "$MIGRATE_FN" response.json
          cat response.json
          FUNCTION_ERROR=$(jq -r '.FunctionError // empty' result.json)
          if [ -n "$FUNCTION_ERROR" ]; then
            echo "❌ Migration Lambda failed"
            exit 1
          fi

      - name: Inject build metadata
        run: |
          COGNITO_DOMAIN=$(aws cloudformation describe-stacks \
            --stack-name $STACK_NAME-prod \
            --query "Stacks[0].Outputs[?OutputKey=='CognitoDomain'].OutputValue" \
            --output text)
          COGNITO_USER_POOL_ID=$(aws cloudformation describe-stacks \
            --stack-name $STACK_NAME-prod \
            --query "Stacks[0].Outputs[?OutputKey=='UserPoolId'].OutputValue" \
            --output text)
          COGNITO_USER_POOL_CLIENT_ID=$(aws cloudformation describe-stacks \
            --stack-name $STACK_NAME-prod \
            --query "Stacks[0].Outputs[?OutputKey=='UserPoolClientId'].OutputValue" \
            --output text)

          echo "COGNITO_DOMAIN: $COGNITO_DOMAIN"

          # api env vars
          echo "AWS_REGION=${{ env.AWS_REGION }}" >> apps/api/.env
          echo "AWS_COGNITO_JWKS_URI=https://cognito-idp.${{ env.AWS_REGION }}.amazonaws.com/${COGNITO_USER_POOL_ID}/.well-known/jwks.json" >> apps/api/.env
          echo "AWS_COGNITO_USER_POOL_URL=https://cognito-idp.${{ env.AWS_REGION }}.amazonaws.com/${COGNITO_USER_POOL_ID}" >> apps/api/.env

          # Web env vars
          echo "VITE_BUILD_ID=${{ github.run_number }}" >> apps/web/.env
          echo "VITE_COMMIT_SHA=${{ github.sha }}" >> apps/web/.env
          echo "VITE_API_BASE_URL=https://2ugomkefji.execute-api.${{ env.AWS_REGION }}.amazonaws.com" >> apps/web/.env
          echo "VITE_AWS_REGION=${AWS_REGION}" >> apps/web/.env
          echo "VITE_COGNITO_USER_POOL_CLIENT_ID=${COGNITO_USER_POOL_CLIENT_ID}" >> apps/web/.env
          echo "VITE_COGNITO_DOMAIN=${COGNITO_DOMAIN}" >> apps/web/.env
          echo "VITE_COGNITO_USER_POOL_ID=${COGNITO_USER_POOL_ID}" >> apps/web/.env

      - name: Install web build dependencies
        run: npm install @rollup/rollup-linux-x64-gnu --workspace apps/web --no-save

      - name: Build frontend
        run: npm run build --workspace apps/web

      - name: Upload frontend to S3
        run: |
          BUCKET=$(aws cloudformation describe-stacks \
            --stack-name $STACK_NAME-prod \
            --query "Stacks[0].Outputs[?OutputKey=='SiteBucketName'].OutputValue" \
            --output text)
          echo "Deploying to $BUCKET"
          aws s3 sync apps/web/dist s3://$BUCKET --delete

      - name: Invalidate CloudFront cache
        run: |
          DIST_ID=$(aws cloudformation describe-stacks \
            --stack-name $STACK_NAME-prod \
            --query "Stacks[0].Outputs[?OutputKey=='SiteDistributionId'].OutputValue" \
            --output text)
          echo "Invalidating distribution $DIST_ID"
          aws cloudfront create-invalidation --distribution-id $DIST_ID --paths "/*"
